#!/bin/bash
# Gitee 推送手动执行脚本
# 由于需要浏览器认证，请手动执行以下步骤

echo "╔══════════════════════════════════════════════════╗"
echo "║     🇨🇳 同步到 Gitee 手动操作指南                   ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "由于 Gitee 需要浏览器认证，请按以下步骤操作："
echo ""
echo "1️⃣  访问 Gitee 并登录"
echo "   https://gitee.com"
echo ""
echo "2️⃣  创建仓库（如未创建）"
echo "   https://gitee.com/new"
echo "   仓库名：emotion-dictionary"
echo "   ⚠️  不要勾选'初始化仓库'"
echo ""
echo "3️⃣  推送代码（在终端执行）"
echo "   cd ~/.openclaw/workspace/skills/emotion-dictionary"
echo "   git remote set-url gitee git@gitee.com:johnyang/emotion-dictionary.git"
echo "   git push -u gitee main"
echo ""
echo "4️⃣  如果提示 SSH key 问题"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   复制输出，添加到：https://gitee.com/profile/sshkeys"
echo ""
echo "══════════════════════════════════════════════════"
echo "完成后，你的 skill 将同时存在于："
echo "   GitHub: https://github.com/johnyang/emotion-dictionary"
echo "   Gitee:  https://gitee.com/johnyang/emotion-dictionary"
echo "══════════════════════════════════════════════════"
